language: erlang
before_install:
  - sudo apt-get install libpam0g-dev
script:
  - make check
otp_release:
  - 22.0
  - 21.3
  - 20.3
  - 19.3
  - 18.3
  # XXX 17.5 is disabled due to an issue with reading records from YAWS; for 
  #     more context, see: https://github.com/rvirding/lfe/issues/380
  # - 17.5
